spring:
  config:
    activate:
      on-profile: dev

  security:
    front:
      cors:
        allowed-origins: "https://plog-dev.duckdns.org" # 프론트 CORS 허용 주소
      frontend-url: https://plog-dev.duckdns.org

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
cookie:
  secure: true
  sameSite: None

logging:
  level:
    com.plog: debug