spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${sm://dev-DB_URL}
      username: ${sm://dev-DB_USERNAME}
      password: ${sm://dev-DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update

logging:
  level:
    com.plog: debug