spring:
  application:
    name: PlogServer
  profiles:
    active: local
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  file:
    path: /var/log/plog
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-5level] %logger{36} - %msg%n'