package com.plog.plogbackend.domain.tag.enums;

public enum PlaceTag {
    GOOD_VIBE("ATMOSPHERE_AND_FOCUS"),
    NOISY("ATMOSPHERE_AND_FOCUS"),
    QUIET("ATMOSPHERE_AND_FOCUS"),
    WHITE_NOISE("ATMOSPHERE_AND_FOCUS"),
    CALM("ATMOSPHERE_AND_FOCUS"),
    IMMERSIVE("ATMOSPHERE_AND_FOCUS"),
    DISTRACTING("ATMOSPHERE_AND_FOCUS"),
    CROWDED("ATMOSPHERE_AND_FOCUS"),
    GOOD_FOR_FOCUS("ATMOSPHERE_AND_FOCUS"),
    BAD_FOR_FOCUS("ATMOSPHERE_AND_FOCUS"),
    PEACEFUL("ATMOSPHERE_AND_FOCUS"),
    TRANQUIL("ATMOSPHERE_AND_FOCUS"),
    SCENIC("ATMOSPHERE_AND_FOCUS"),
    COZY("ATMOSPHERE_AND_FOCUS"),
    MODERATE_NOISE("ATMOSPHERE_AND_FOCUS"),

    FAST_WIFI("WORK_CONVENIENCE"),
    UNSTABLE_WIFI("WORK_CONVENIENCE"),
    NO_WIFI("WORK_CONVENIENCE"),
    PRINTING_AVAILABLE("WORK_CONVENIENCE"),
    MANY_OUTLETS("WORK_CONVENIENCE"),
    NO_OUTLETS("WORK_CONVENIENCE"),
    CHARGING_AVAILABLE("WORK_CONVENIENCE"),
    NO_CHARGING("WORK_CONVENIENCE"),
    LAPTOP_FRIENDLY("WORK_CONVENIENCE"),
    NO_LAPTOPS("WORK_CONVENIENCE"),
    LONG_WORK("WORK_CONVENIENCE"),
    SHORT_WORK("WORK_CONVENIENCE"),

    COMFORTABLE_SEATS("SEATING_AND_SPACE"),
    UNCOMFORTABLE_SEATS("SEATING_AND_SPACE"),
    WINDOW_SEATS("SEATING_AND_SPACE"),
    MANY_SEATS("SEATING_AND_SPACE"),
    FEW_SEATS("SEATING_AND_SPACE"),
    WIDE_SEAT_SPACING("SEATING_AND_SPACE"),
    NARROW_SEAT_SPACING("SEATING_AND_SPACE"),
    LARGE_TABLES("SEATING_AND_SPACE"),
    SMALL_TABLES("SEATING_AND_SPACE"),
    SINGLE_SEATS("SEATING_AND_SPACE"),
    EIGHT_PERSON_SEATS("SEATING_AND_SPACE"),
    SPACIOUS("SEATING_AND_SPACE"),
    NARROW_SPACE("SEATING_AND_SPACE"),
    CONVENIENT_LAYOUT("SEATING_AND_SPACE"),

    WARM("ENVIRONMENT_AND_COMFORT"),
    COOL("ENVIRONMENT_AND_COMFORT"),
    GOOD_TEMPERATURE("ENVIRONMENT_AND_COMFORT"),
    CLEAN("ENVIRONMENT_AND_COMFORT"),
    MESSY("ENVIRONMENT_AND_COMFORT"),
    GOOD_VENTILATION("ENVIRONMENT_AND_COMFORT"),
    BAD_VENTILATION("ENVIRONMENT_AND_COMFORT"),
    BRIGHT_LIGHTING("ENVIRONMENT_AND_COMFORT"),
    DARK_LIGHTING("ENVIRONMENT_AND_COMFORT"),
    GOOD_SUNLIGHT("ENVIRONMENT_AND_COMFORT"),
    PLEASANT("ENVIRONMENT_AND_COMFORT"),
    STUFFY("ENVIRONMENT_AND_COMFORT"),

    PARKING_AVAILABLE("OTHER"),
    NO_PARKING("OTHER"),
    MEETING_ROOM("OTHER"),
    CONVERSATION_FRIENDLY("OTHER"),
    OVERNIGHT_WORK("OTHER");

    private final String status;

    PlaceTag(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }
}

