server {
    listen 80;

    client_max_body_size 60M;

    location ~* \.(php|asp|aspx|jsp|env|cgi|bak|log)$ {
        return 444;
    }

    location ~* /(wp-admin|phpmyadmin|config|setup) {
        return 444;
    }

    location / {
        proxy_pass http://spring:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # 외부 프록시(Cloudflare, AWS ALB 등)가 HTTPS로 넘겨준 X-Forwarded-Proto 값을 그대로 유지
        set $my_scheme $scheme;
        if ($http_x_forwarded_proto != "") {
            set $my_scheme $http_x_forwarded_proto;
        }
        proxy_set_header X-Forwarded-Proto $my_scheme;
    }
}